services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: ["python", "app.py"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/mass_spectrum_db.sql:/docker-entrypoint-initdb.d/mass_spectrum_db.sql
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD-SHELL", "psql -U massbank_user -d massbank -c 'SELECT COUNT(*) FROM spectrum_data;' 2>/dev/null | grep -E '^[[:space:]]*[1-9][0-9]{6}' || exit 1"] # wait for 7 digit number (millions of rows)
      interval: 60s
      timeout: 10s
      retries: 25
      start_period: 300s
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
