name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "FLASK_ENV=development" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=postgres" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Download database file
        run: |
          curl -L -o db/mass_spectrum_db.sql \
          https://github.com/NicolasMurphy/mass-spectrum-to-audio-converter/releases/download/2025-08-19/mass_spectrum_db.sql

      - name: Start services
        run: docker compose up -d

      - name: Run backend tests
        run: docker compose exec -T app python -m pytest tests/ -v -s --cov=. --cov-report=term-missing

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Playwright dependencies
        run: |
          cd tests/e2e
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd tests/e2e
          npm run test

      - name: Cleanup
        if: always()
        run: docker compose down -v
